// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"apiTools/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/query/List",
				Handler: QueryDTlistHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/send/msg",
				Handler: SendMsgHandler(serverCtx),
			},
		},
	)
}
