// Code generated by goctl. DO NOT EDIT.
package types

type UserInfo struct {
	Id   int64  `path:"id"`
	Name string `json:"name"`
	Age  int    `json:"age"`
}

type QueryDT_dailyTradeReq struct {
	StartDate string `json:"startdate"`
	EndDate   string `json:"enddate"`
	Domain    string `json:"domain"`
}

type QueryDT_dailyTradeResp struct {
	Base
	Data UserInfo `json:"data"`
}

type Request struct {
	Name string `json:"name"`
}

type Response struct {
	Message string `json:"message"`
}

type Base struct {
	Code int64  `json:"code"`
	Msg  string `json:"msg"`
}
